### ISSUE TITLE
[Feature] SQL User Authentication

### ISSUE THREAD

**Issue by dropitlikecross** [katznboyz1/youtube-dl-server#8]
Rather than local user authentication, how about sql authentication?

**Comment by renamedquery** [comment]
What do you mean by this? At the moment, the credentials are stored in the database, and the users are authenticated server side whenever an action happens. Is there a separate method of authentication within sql?
Sorry for the late response.

**Comment by dropitlikecross** [comment]
Sorry, I meant to say web authentication* this way you could let people register themselves.

**Comment by renamedquery** [comment]
Oh I see, no worries. I was thinking of this, but the issue is that if you have it exposed to the internet, anybody would be able to register an account and use your bandwidth and compute to download videos. I guess a way to circumvent this could be to use a special code for registration, but I haven't worked out a good system for that yet, so for now registration can be done by admins only. If I think of a good way to get it to work, I can definitely try it out.

**Comment by dropitlikecross** [comment]
I think an invite system would be pretty cool, I've seen some pretty good open source projects on github.

**Comment by renamedquery** [comment]
I'll take a look soon, I like that idea!

**Comment by renamedquery** [comment]
Just added a registration system in the latest commit. You can easily register users by going to Admin>User Registration, then copying one of the keys and making a URL like `your.internal.ip.address:port/register?rk=key`. Example URL: `http://192.168.32.123:8080/register?rk=059def66a01ef12c5465735793a61acb66355eb738b7968cb8bb88aee0ab9166`. This will drop the new user on the register page, and they will be able to register an account. They can also manually enter the registration key, but using the URL is easier since it autofills the key for them (and you can turn the URL into a QR code for easy access).
